version: '3'

services:
  backend:
    build:
      context: ./forumserver
    command: /bin/sh /opt/uwsgi/start_server.sh
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./forum
    volumes:
      - react_build:/forum/build
    command: yarn start
    ports:
      - 3000:3000
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/forum
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
